### ISSUE TITLE
[Dashboard] Dashboard tab give me error 500.

### ISSUE THREAD

**Issue by R3TR0V1P3R** [AAA3A-AAA3A/Red-Dashboard#1]
Hello i finnaly got the bot setup after using your setup.py bt could u please help me get the webdashboard tab working idk if it something i did or what but this is what it gives me.
![Error 500 Red-Dashboard](https://github.com/AAA3A-AAA3A/Red-Dashboard/assets/87746587/300bfedf-1791-4593-a5f6-999e45ef64cd)

**Comment by AAA3A-AAA3A** [comment]
Hello, what is the error please?

**Comment by R3TR0V1P3R** [comment]
Hey so everytime I click on the discord dashboard I get error 500 would u like me to send a picture of the terminal window that the red-dashboard is running in

**Comment by AAA3A-AAA3A** [comment]
Try updating the webserver now.
